console.log("Exercise - 1");
console.log("Swap variables");
let a = 1;
let b= 2;
console.log(a, b);
console.log("method 1:Destructuring assignment");
console.log("swap 1 va 2");
[a,b] = [b,a];
console.log(a, b);
// a = a + b;
// b = a - b;
// a = a- b;
// console.log(a, b);
