let movies = ['bỗng dưng muốn khóc','về nhà đi con','bí mật tam giác vàng'];
console.log(movies);
let newMovies = prompt("Enter new movies to add");
movies.push(newMovies);
console.log9(movies);
let index = prompt("Enter index in array");
console.log(movies[index]);
let uMovie = prompt("Enter movie title");
movies[0] = uMovie;
console.log(movies);
let index = Number(prompt("Enter position to update"));
let uMovie1 = prompt("Enter movie to update");
movies[index] = uMovie1;
console.log(movies);
let index1 = Number(prompt("Enter position to delete"));
movies.splice(index1,1);
console.log(movies);
let index2 = Number(prompt("Enter position to delete"));
let n = Number(prompt("Enter number movie delete"));
movies.splice(index2,n);
console.log(movies);